# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: virtual_insanity
email: thyagobr@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Blog pessoal de Thyago Barbosa Rodrigues
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://thyagobr.github.io"
twitter_username: thyagobr
github_username:  thyagobr
google_analytics: UA-108245567-1

# Build settings
markdown: kramdown
theme: jekyll-theme-midnight
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
